name: dart_codecov_generator
version: 0.4.0
description: Generates lcov and/or HTML coverage reports for Dart projects. (UNIX only)
authors:
  - John Ryan <john.p.ryan4@gmail.com>
  - Evan Weible <ekweible@gmail.com>
homepage: https://github.com/codecov/dart
dependencies:
  args: "^1.5.0"
  logging: ">=0.9.0 <0.12.0"
  path: ">=1.6.3"
dev_dependencies:
  coverage: "0.13.11"
  test: "1.12.0"
executables:
  dart_codecov_generator:
  generate_coverage:
