dist: bionic
language: ruby
addons:
  apt:
    packages:
      - libdigest-sha-perl
      - shunit2
notifications:
  email: false
sudo: false
script:
  # Confirm tests pass first
  - env -i PATH="$PATH" tests/test
  # Run the source through ShellCheck (http://www.shellcheck.net).
  - env -i PATH="$PATH" shellcheck codecov tests/test

  - shasum --algorithm 1 --check --strict ./SHA1SUM
  - shasum --algorithm 256 --check --strict ./SHA256SUM
  - shasum --algorithm 512 --check --strict ./SHA512SUM
