language: ruby
rvm: 2.6.3
before_install:
  - gem update --system
  - gem install bundler
install:
  - gem install rails
script:
  - bundle update --bundler
  - bundle install
  - bundle exec rspec
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.xml
  - ruby request.rb
