language: node_js

node_js: node

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install
  - npm install -g codecov
  - npm install -g request

script:
  - npm t
  - codecov -f ./coverage/coverage-final.json
  - node request.js
