apiVersion: v1
kind: Service
metadata:
  annotations: {{ .Values.annotations }}
  name: web
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: web
  type: NodePort
