apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - args:
        - web
        env:
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: codecov/enterprise-web:v{{ .Values.codecovVersion }}
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: 
          limits:
            cpu: {{ .Values.web.resources.limits.cpu }}
            memory: {{ .Values.web.resources.limits.memory }}
          requests:
            cpu: {{ .Values.web.resources.requests.cpu }}
            memory: {{ .Values.web.resources.requests.memory }}
        volumeMounts:
        - mountPath: /config
          name: codecov-yml
          readOnly: true
        - mountPath: /cert
          name: scm-ca-cert
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: codecov-yml
        secret:
          secretName: codecov-yml
      - name: scm-ca-cert
        secret:
          secretName: scm-ca-cert
