apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - args:
        - worker
        - --queue celery,uploads
        - --concurrency 1
        env:
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: codecov/enterprise-worker:v{{ .Values.codecovVersion }}
        imagePullPolicy: Always
        name: workers
        resources:
          limits: 
            cpu: {{ .Values.worker.resources.limits.cpu }}
            memory: {{ .Values.worker.resources.limits.memory }}
          requests:
            cpu: {{ .Values.worker.resources.requests.cpu }}
            memory: {{ .Values.worker.resources.requests.memory }}
        volumeMounts:
        - mountPath: /config
          name: codecov-yml
          readOnly: true
      volumes:
      - name: codecov-yml
        secret:
          secretName: codecov-yml
